12 filters in url param
bruin-tennis-consulting/match-manager pull request #210
Opened 2024-10-22 03:17 UTC by krish1925

Solves issue number #12 . Tested on the main branch

2024-10-22 19:51 UTC, Fredenck requested changes

2024-10-22 19:51 UTC, Fredenck commented on .vscode/settings.json
> +    "source.fixAll": "explicit",
make sure not to commit your vscode settings as people will have different configs. the current one auto-formats for prettier/eslint on save so revert this change please

2024-10-22 19:51 UTC, Fredenck commented on app/components/FilterList.js
> +// need to add functionality such that the
such that the ...?

2024-10-22 19:51 UTC, Fredenck commented on app/components/FilterList.js
> +  }, [setFilterList])
change the dependency list to []. This is more clear and runs on the initial render. 

This is also buggy: If I go to http://localhost:3000/matches/Z6F1Amn51528fzmVlHlV?player1ServePlacement=Deuce%3A+Body the filters are not applied. I have to click on the filters tab, then the state is updated.

2024-10-22 20:32 UTC, krish1925 commented on .vscode/settings.json
> +    "source.fixAll": "explicit",
Yes I had this installed for some other project and accidentally committed this to repo, I'll make sure not to commit that

2024-10-31 01:39 UTC, Fredenck commented
make sure you run `git merge development` to resolve merge conflicts

2024-11-19 05:19 UTC, ritzz26 commented
@Fredenck @krish1925 is this still something we are working on ?

2024-11-20 02:25 UTC, Fredenck commented
talked to Krish about it, but here's the tldr: yes still being worked on, some more testing needs to be done after the recent changes (deletion of extractSetScores), new Firebase data format, etc

2025-01-14 01:04 UTC, krish1925 commented
Fixed all merge conflicts in new branch: 12-Filters-in-URL-Param-new

2025-01-17 01:53 UTC, Fredenck commented
redone with #264

2025-01-17 01:53 UTC, closed without merging