Merged MatchDataProvider and DatabaseProvider into DataProvider
bruin-tennis-consulting/match-manager pull request #211
Opened 2024-10-22 22:29 UTC by bzhang102

- Combined MatchDataProvider and DatabaseProvider contexts into single new context named DataProvider
- Renamed/repointed all occurrences to point
- Tested locally
<img width="499" alt="image" src="https://github.com/user-attachments/assets/c79f1f72-d715-477f-adcf-84b87d91a4eb">

2024-10-25 00:35 UTC, Fredenck requested changes
mostly looks good. Make sure you run `git merge development` so your local changes are synced with development. The filtering for schools should be live: this decreases initial load time as we only display the latest school played rather than waiting to render all of the previous schools we've played

2024-11-05 01:19 UTC, bzhang102 commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
ok, merge conflict fixed, should be okay now. can you take a look to see if it's done right? want to be sure i didn't break anything lol

2024-11-05 19:44 UTC, Fredenck requested changes
make sure you test your changes with `npm run dev`. looks like you missed updating the import statement for match-list.

2024-11-14 18:29 UTC, Fredenck approved these changes
nice

2024-11-14 18:29 UTC, merged