Added win/point percentage next to subfilter.
bruin-tennis-consulting/match-manager pull request #58
Opened 2024-02-01 10:42 UTC by kesdlvi

Closes #14 

Percentages are rounded to the nearest integer. We could also make it a fraction (i.e. filtered points / total points), but there are some slight styling issues. 

<img width="227" alt="Screenshot 2024-02-01 at 2 36 36 AM" src="https://github.com/awest25/Tennis-Video-Viewer/assets/85363542/d9fb0168-bb62-402b-b5d2-58f66c7f0859">

2024-02-01 22:48 UTC, kesdlvi commented
Some filters are than 1% (for example one filters actual percentage is .877%). I was thinking for these filters it would be better to just have something like "<1%" instead of rounding up.

2024-02-06 03:34 UTC, Fredenck commented
looks good. Make sure to check all of your changes before committing; there's a few random spaces here and there
<img width="1074" alt="image" src="https://github.com/awest25/Tennis-Video-Viewer/assets/40157329/d375d7b3-0dc3-43f3-9b5a-907d48adc06d">
and 
<img width="1067" alt="image" src="https://github.com/awest25/Tennis-Video-Viewer/assets/40157329/e8b6b056-a5c1-42eb-a00b-7d255b926562">

2024-02-06 03:38 UTC, Fredenck commented
Also, I'm assuming d3 is a library?

Can you also include the version in package.json so everyone is on the same node_modules

2024-02-06 03:40 UTC, Fredenck requested changes
see comments

2024-02-06 04:06 UTC, awest25 commented
This is good but there are a couple more things:
- Since the percentages are not really useful to the player (easy to get confused), it's mostly for our visualization team. So could you hide the option to display the percentages behind an "options" menu?
- When empty string is an option (so like not every point will have a return error), don't include it in the percentage calculation. So all the visible percentages should add up to 100. See below.

Here's an example of what the options menu might look like, either location works, to what you see fit:
<img width="782" alt="Screenshot 2024-02-05 at 7 40 25 PM" src="https://github.com/awest25/Tennis-Video-Viewer/assets/93575706/39db5c60-bf93-4c95-8fd7-72acf0a87abd">

And here's the second issue I'm describing:
<img width="218" alt="IMG_4706" src="https://github.com/awest25/Tennis-Video-Viewer/assets/93575706/f78ec94a-67c8-444b-91c9-031d9c42eaf2">

2024-02-06 04:07 UTC, awest25 reviewed
see my comment

2024-02-06 04:08 UTC, awest25 commented
also i think the d3 line is a typo so pls remove

2024-02-07 22:54 UTC, merged